import type { Book, Verse } from "./types";

type BookTuple = [
  id: string,
  testament: "old" | "new",
  nameKo: string,
  nameEn: string,
  chapterCount: number,
];

const bookTuples: BookTuple[] = [
  ["gen", "old", "창세기", "Genesis", 50],
  ["exo", "old", "출애굽기", "Exodus", 40],
  ["lev", "old", "레위기", "Leviticus", 27],
  ["num", "old", "민수기", "Numbers", 36],
  ["deu", "old", "신명기", "Deuteronomy", 34],
  ["jos", "old", "여호수아", "Joshua", 24],
  ["jdg", "old", "사사기", "Judges", 21],
  ["rut", "old", "룻기", "Ruth", 4],
  ["1sa", "old", "사무엘기상", "1 Samuel", 31],
  ["2sa", "old", "사무엘기하", "2 Samuel", 24],
  ["1ki", "old", "열왕기상", "1 Kings", 22],
  ["2ki", "old", "열왕기하", "2 Kings", 25],
  ["1ch", "old", "역대기상", "1 Chronicles", 29],
  ["2ch", "old", "역대기하", "2 Chronicles", 36],
  ["ezr", "old", "에스라", "Ezra", 10],
  ["neh", "old", "느헤미야", "Nehemiah", 13],
  ["est", "old", "에스더", "Esther", 10],
  ["job", "old", "욥기", "Job", 42],
  ["psa", "old", "시편", "Psalms", 150],
  ["pro", "old", "잠언", "Proverbs", 31],
  ["ecc", "old", "전도서", "Ecclesiastes", 12],
  ["sng", "old", "아가", "Song of Solomon", 8],
  ["isa", "old", "이사야", "Isaiah", 66],
  ["jer", "old", "예레미야", "Jeremiah", 52],
  ["lam", "old", "예레미야애가", "Lamentations", 5],
  ["ezk", "old", "에스겔", "Ezekiel", 48],
  ["dan", "old", "다니엘", "Daniel", 12],
  ["hos", "old", "호세아", "Hosea", 14],
  ["jol", "old", "요엘", "Joel", 3],
  ["amo", "old", "아모스", "Amos", 9],
  ["oba", "old", "오바댜", "Obadiah", 1],
  ["jon", "old", "요나", "Jonah", 4],
  ["mic", "old", "미가", "Micah", 7],
  ["nam", "old", "나훔", "Nahum", 3],
  ["hab", "old", "하박국", "Habakkuk", 3],
  ["zep", "old", "스바냐", "Zephaniah", 3],
  ["hag", "old", "학개", "Haggai", 2],
  ["zec", "old", "스가랴", "Zechariah", 14],
  ["mal", "old", "말라기", "Malachi", 4],
  ["mat", "new", "마태복음", "Matthew", 28],
  ["mrk", "new", "마가복음", "Mark", 16],
  ["luk", "new", "누가복음", "Luke", 24],
  ["jhn", "new", "요한복음", "John", 21],
  ["act", "new", "사도행전", "Acts", 28],
  ["rom", "new", "로마서", "Romans", 16],
  ["1co", "new", "고린도전서", "1 Corinthians", 16],
  ["2co", "new", "고린도후서", "2 Corinthians", 13],
  ["gal", "new", "갈라디아서", "Galatians", 6],
  ["eph", "new", "에베소서", "Ephesians", 6],
  ["php", "new", "빌립보서", "Philippians", 4],
  ["col", "new", "골로새서", "Colossians", 4],
  ["1th", "new", "데살로니가전서", "1 Thessalonians", 5],
  ["2th", "new", "데살로니가후서", "2 Thessalonians", 3],
  ["1ti", "new", "디모데전서", "1 Timothy", 6],
  ["2ti", "new", "디모데후서", "2 Timothy", 4],
  ["tit", "new", "디도서", "Titus", 3],
  ["phm", "new", "빌레몬서", "Philemon", 1],
  ["heb", "new", "히브리서", "Hebrews", 13],
  ["jas", "new", "야고보서", "James", 5],
  ["1pe", "new", "베드로전서", "1 Peter", 5],
  ["2pe", "new", "베드로후서", "2 Peter", 3],
  ["1jn", "new", "요한일서", "1 John", 5],
  ["2jn", "new", "요한이서", "2 John", 1],
  ["3jn", "new", "요한삼서", "3 John", 1],
  ["jud", "new", "유다서", "Jude", 1],
  ["rev", "new", "요한계시록", "Revelation", 22],
];

export const bibleBooks: Book[] = bookTuples.map(
  ([id, testament, nameKo, nameEn, chapterCount], index) => ({
    id,
    testament,
    nameKo,
    nameEn,
    chapterCount,
    order: index + 1,
  }),
);

function verse(id: string, bookId: string, chapter: number, verseNumber: number, text: string): Verse {
  return {
    id,
    bookId,
    chapter,
    verse: verseNumber,
    text,
    translation: "KJV 흠정역 v0 fixture",
  };
}

export const fixtureVerses: Verse[] = [
  verse("gen-1-1", "gen", 1, 1, "샘플 본문: 창조의 시작을 기록하는 임시 구절입니다."),
  verse("gen-1-2", "gen", 1, 2, "샘플 본문: 혼돈과 어둠 가운데 하나님의 영을 묵상하는 임시 구절입니다."),
  verse("gen-1-3", "gen", 1, 3, "샘플 본문: 빛이 선포되는 장면을 위한 임시 구절입니다."),
  verse("gen-1-4", "gen", 1, 4, "샘플 본문: 빛과 어둠이 구별되는 흐름을 담은 임시 구절입니다."),
  verse("gen-1-5", "gen", 1, 5, "샘플 본문: 첫째 날의 마침을 나타내는 임시 구절입니다."),
  verse("gen-1-6", "gen", 1, 6, "샘플 본문: 궁창을 언급하는 리더 테스트용 임시 구절입니다."),
  verse("gen-1-7", "gen", 1, 7, "샘플 본문: 위와 아래를 나누는 장면을 위한 임시 구절입니다."),
  verse("gen-1-8", "gen", 1, 8, "샘플 본문: 둘째 날의 마침을 나타내는 임시 구절입니다."),
  verse("gen-1-9", "gen", 1, 9, "샘플 본문: 물과 마른 땅을 구분하는 임시 구절입니다."),
  verse("gen-1-10", "gen", 1, 10, "샘플 본문: 땅과 바다의 이름을 확인하는 임시 구절입니다."),
  verse("gen-3-15", "gen", 3, 15, "샘플 본문: 약속과 소망을 표시하기 위한 임시 구절입니다."),
  verse("exo-12-1", "exo", 12, 1, "샘플 본문: 출애굽 사건의 장면을 여는 임시 구절입니다."),
  verse("exo-12-2", "exo", 12, 2, "샘플 본문: 새 시작과 달력을 다루는 임시 구절입니다."),
  verse("exo-12-3", "exo", 12, 3, "샘플 본문: 가정 단위 준비를 나타내는 임시 구절입니다."),
  verse("psa-23-1", "psa", 23, 1, "샘플 본문: 목자와 인도하심을 묵상하기 위한 임시 구절입니다."),
  verse("psa-23-2", "psa", 23, 2, "샘플 본문: 쉼과 평안을 표현하는 임시 구절입니다."),
  verse("psa-23-3", "psa", 23, 3, "샘플 본문: 회복과 의의 길을 다루는 임시 구절입니다."),
  verse("psa-23-4", "psa", 23, 4, "샘플 본문: 두려움 속에서도 위로를 확인하는 임시 구절입니다."),
  verse("psa-23-5", "psa", 23, 5, "샘플 본문: 공급과 넘침을 묵상하는 임시 구절입니다."),
  verse("psa-23-6", "psa", 23, 6, "샘플 본문: 선하심과 긍휼을 바라보는 임시 구절입니다."),
  verse("jhn-3-16", "jhn", 3, 16, "샘플 본문: 복음의 핵심 구절 자리에 들어갈 임시 본문입니다."),
  verse("jhn-3-17", "jhn", 3, 17, "샘플 본문: 구원과 심판의 흐름을 확인하는 임시 구절입니다."),
  verse("rom-10-9", "rom", 10, 9, "샘플 본문: 고백과 믿음을 분류하기 위한 임시 구절입니다."),
  verse("rom-10-10", "rom", 10, 10, "샘플 본문: 마음과 입의 고백을 다루는 임시 구절입니다."),
  verse("rev-22-1", "rev", 22, 1, "샘플 본문: 마지막 장 탐색을 검증하기 위한 임시 구절입니다."),
  verse("rev-22-2", "rev", 22, 2, "샘플 본문: 생명과 회복의 이미지를 담은 임시 구절입니다."),
];
